### ISSUE TITLE
Product page

### ISSUE THREAD

**Issue by talrez11** [Way2CU/Duki-Napo-Store#26]
1.Product images should fill more then half of section width.Product explanation should be narrow
2.Product images should not open lightbox but should switch bigger image placeholder.
3.Product properties should be removed except: size, wight and price all other information should be written on product text description.
4.Rings sizes and pendants sizes should be set as shown on: http://www.bleeckerandprince.com/ site.
5.Add service contact form for each product if user has questions.A button to open that form should be added after product text description

**Comment by iliyaM** [comment]
updated
