### ISSUE TITLE
tranzila doesnt send invoice upon purchase

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Duki-Napo-Store#31]
I purchase and didnt get an invoice

**Comment by MeanEYE** [comment]
Why Tranzila doesn't send I don't know. Perhaps there's an attribute which I need to send them? Can this be checked somehow as they lack any form of documentation.

**Comment by hanan-avzuk** [comment]
Tranzila does send now.
We need a simple solution so if the client sets the purchase info to be Israel then we send Tranzila that price include vat and so the invoice will be with vat... else we should send them that amount is as is and no need to calculate or include vat. Notice that in both cases the price stays the same, meaning that for a product that is 1170$ both Israeli client and other will pay 1170$, but Israeli client will see 1000$ and 170$ vat and other clients will see 1170$ as total and vat will be 0%.

**Comment by MeanEYE** [comment]
This is a separate issue. Unrelated to this one.
