### ISSUE TITLE
Item details on tablet need optimization.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Duki-Napo-Store#33]
![whatsapp image 2016-12-05 at 13 04 00 1](https://cloud.githubusercontent.com/assets/1911594/20884572/4f574520-baec-11e6-8d02-6bada196981a.jpeg)
![whatsapp image 2016-12-05 at 13 04 00](https://cloud.githubusercontent.com/assets/1911594/20884573/4f79b5e2-baec-11e6-96d0-82a4edd90348.jpeg)
As seen on images top menu and other things need to be fixed to look good on tablet.

**Comment by MeanEYE** [comment]
Also, ignore the shoes and the fact person is holding tablet upside down. We'll just attribute those to excitement for looking at one of our sites.

**Comment by iliyaM** [comment]
lol. changes are done and waiting for deployment
