### ISSUE TITLE
Show google map with their location on contact age

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Duki-Napo-Store#34]

**Comment by MeanEYE** [comment]
@iliyaM see with Michael if there's a need for live map or image is good enough.

**Comment by hanan-avzuk** [comment]
Live map

**Comment by MeanEYE** [comment]
In that case we need a coordinates.

**Comment by iliyaM** [comment]
live map with favicon icon for the location
![screenshot from 2016-12-07 17-00-59](https://cloud.githubusercontent.com/assets/20294485/20972821/cf0b7c9c-bc9e-11e6-9390-a3738ddd0c57.png)

**Comment by MeanEYE** [comment]
All doable through maps API and their [custom markers](https://developers.google.com/maps/documentation/javascript/custom-markers).

**Comment by iliyaM** [comment]
![screenshot from 2016-12-08 10-02-25](https://cloud.githubusercontent.com/assets/20294485/21002311/c51de08c-bd2d-11e6-9ad1-f7c00019caaa.png)
