### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Duki-Napo-Store#35]
Misha sent a design

**Comment by iliyaM** [comment]
done
![screenshot from 2016-12-08 14-22-19](https://cloud.githubusercontent.com/assets/20294485/21009900/c4e12600-bd51-11e6-9710-3c32f50b86e5.png)

**Comment by MeanEYE** [comment]
Don't mark them as done yet as they will need to be modified slightly once I finish implementation. And this is not a good design one bit. Who the fuck knows what 404 means? We should just state plainly that page user was looking for was not found.

**Comment by iliyaM** [comment]
![screenshot from 2016-12-08 15-17-34](https://cloud.githubusercontent.com/assets/20294485/21011339/78922f80-bd59-11e6-9f1f-4eed22b7f8c6.png)

**Comment by MeanEYE** [comment]
I've created system language constant under `message_client_error_404`. Use that one instead of this.

**Comment by iliyaM** [comment]
![screenshot from 2016-12-11 10-28-10](https://cloud.githubusercontent.com/assets/20294485/21079010/8b13b89c-bf8c-11e6-9c26-eb71d89fbf5f.png)

**Comment by iliyaM** [comment]
![screenshot from 2016-12-11 11-01-58](https://cloud.githubusercontent.com/assets/20294485/21079165/421404b2-bf91-11e6-827b-e987a63f5e47.png)

**Comment by MeanEYE** [comment]
You don't have to post screen shot every time. It's fine like this.
