### ISSUE TITLE
Ligthbox close button image is not shown on any of our live site

### ISSUE THREAD

**Issue by talrez11** [Way2CU/Duki-Napo-Store#38]
http://dukivenapo.com/modules/gallery/collection/images/close_button.svg Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://dukivenapo.com/modules/gallery/backend/images/loading.gif Failed to load resource: the server responded with a status of 500 (Internal Server Error).

This is very annoying, because every client complains about this issue

**Comment by MeanEYE** [comment]
Should be reported on Caracal then. But I know.
