### ISSUE TITLE
Show sold items

### ISSUE THREAD

**Issue by talrez11** [Way2CU/Duki-Napo-Store#39]
Client asked to have the ability for showing some kind of a label if item is sold out.
Do you have any suggestion for dedicating some param in order to show that request?

**Comment by MeanEYE** [comment]
We don't have stock management at the moment.

**Comment by talrez11** [comment]
Is there any solution in the meanwhile?

**Comment by MeanEYE** [comment]
@hanan-avzuk needs to confirm we are to deal with this issue at all. This wasn't part of the initial spec.

**Comment by talrez11** [comment]
After talking with michal from duki this morning she need this done asap. We need to think of a solution for that one

**Comment by MeanEYE** [comment]
There's solution on Bali-Shuk for this. They have per user all the transactions and individual items.
