### ISSUE TITLE
Uploaded images are not shown 

### ISSUE THREAD

**Issue by talrez11** [Way2CU/Duki-Napo-Store#40]
When loading images to gallery, images are not updated on the gallery itself. only on refresh you can see them.

**Comment by MeanEYE** [comment]
@talrez11 you mean backend window doesn't show them?

**Comment by talrez11** [comment]
Yes, i think same issue was on bsexy site

**Comment by MeanEYE** [comment]
Does this by any chance happen when you upload multiple images, or it's present with single image upload as well?

**Comment by talrez11** [comment]
Checked it, and it happens when trying to upload one image as well

**Comment by talrez11** [comment]
I should point out that it does not occur on every instance but it does happen from time to time

**Comment by MeanEYE** [comment]
So, the proper behavior should be like this. You upload image and window dialog changes to message notifying you of upload success. After closing that window, original gallery needs to update. Issue is that this update sometimes doesn't happen?

**Comment by talrez11** [comment]
Most of the time that behaviour doesnt happen, also window dialog does not change the message, it is stcuk with the title

**Comment by MeanEYE** [comment]
Title is not suppose to change. Only thing that should change is the content of the window and should state message about operation success.

**Comment by talrez11** [comment]
Well, those things are not happening, so thats what need to be fixed!
