### ISSUE TITLE
Empty label on mobile menu.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Duki-Napo-Store#5]
There's a missing text on mobile menu. Most likely due to misnamed text constant.
![screenshot from 2015-11-22 15-06-53](https://cloud.githubusercontent.com/assets/1911594/11324183/bce006a0-912a-11e5-9b8d-79f6fa46dc39.png)

**Comment by MeanEYE** [comment]
![screenshot from 2015-11-22 15-41-43](https://cloud.githubusercontent.com/assets/1911594/11324351/91af57ec-912f-11e5-9d36-6aee2ded0a45.png)
For lazy people who are too important to be bothered to inspect elements.

**Comment by talrez11** [comment]
Added label on mobile menu
